import {SanPhAm} from "./sanpham";
import {QuanLySanPhAm} from "./quanlysanpham";
let quanLySanPhAm = new QuanLySanPhAm();
let sAnpHam1 = new SanPhAm(1,"dienthoai1",300,5,"nokia");
let sAnpHam2 = new SanPhAm(2,"dienthoai2",500,12,"SamSung");
let sAnpHam3 = new SanPhAm(3,"dienthoai3",200,11,"IPhone");
let sAnpHam4 = new SanPhAm(4,"dienthoai4",600,4,"HTC");
let sAnpHam5 = new SanPhAm(5,"dienthoai5",900,8,"IPhone");
let sAnpHam6 = new SanPhAm(6,"dienthoai6",700,6,"Bphone");
quanLySanPhAm.add(sAnpHam1);
quanLySanPhAm.add(sAnpHam2);
quanLySanPhAm.add(sAnpHam3);
quanLySanPhAm.add(sAnpHam4);
quanLySanPhAm.add(sAnpHam5);
console.log(quanLySanPhAm);
quanLySanPhAm.editSanPhAm(3,sAnpHam6);
console.log(quanLySanPhAm);
quanLySanPhAm.remove(1);
console.log(quanLySanPhAm);
quanLySanPhAm.searchKhoAngGia(500,700);
console.log(quanLySanPhAm);
quanLySanPhAm.giaTangDan();
console.log(quanLySanPhAm);
console.log(quanLySanPhAm.giaGiAmDan());
console.log(quanLySanPhAm.soLuOngGiAmDan());
quanLySanPhAm.searchTheoHang("IPhone");
console.log(quanLySanPhAm);